
-- Schema:  oltp; 
-- Version: V0.09_20210505;
-- Author/Date: cfchen/20210505;
-- Purpose: Oltp資料表;
-- Table: sbd_ifxt100_h01;
-- Compressed: N ;
-- Distributed: Y (rfn);
-- Partition: N ;
-- Constraint: N

---- Compressed Example: WITH (APPENDONLY=true, COMPRESSLEVEL=1, COMPRESSTYPE=quicklz, OIDS=FALSE)
---- Partition Example: PARTITION BY RANGE(DATA_YM) (PARTITION P201501 START ('2015-01-01'::date) END ('2015-02-01'::date) , ... )
---- Distributed Example: DISTRIBUTED BY (BAN)
---- Naming Convention: P -> pk, U -> uk

DROP TABLE IF EXISTS  oltp.sbd_ifxt100_h01;

CREATE TABLE  oltp.sbd_ifxt100_h01 (
rfn varchar(17) NOT NULL,
cal_tax_mode varchar(1) ,
fam_rate decimal(3,1) ,
slry_spr_rate decimal(3,1) ,
xmp_a_70_pers_cnt decimal(2,0) ,
xmp_b_70_pers_cnt decimal(2,0) ,
apl_incm_t decimal(14,0) ,
gene_ded_amt decimal(14,0) ,
slry_ded decimal(14,0) ,
prop_loss_ded decimal(14,0) ,
saving_ded decimal(14,0) ,
disab_pers_cnt decimal(2,0) ,
tuition_ded decimal(14,0) ,
apl_incm_n decimal(14,0) ,
apl_tax decimal(14,0) ,
apl_invt_ded_amt decimal(14,0) ,
rebuy_slf_ded decimal(14,0) ,
apl_divd_pf_rbt_tax decimal(14,0) ,
apl_pt_crd decimal(14,0) ,
apl_incm_wh_tax decimal(14,0) ,
tps_incm_tot decimal(14,0) ,
ss_incm_tot decimal(14,0) ,
flg_slf_pay decimal(14,0) ,
sh_sup_ref decimal(14,0) ,
paid_sup_tax decimal(14,0) ,
refd_tax decimal(14,0) ,
zst_sh_sup_ref decimal(14,0) ,
manage_cd varchar(24) ,
iit_adj_reas varchar(13) ,
coll_mk varchar(1) ,
pr_mk varchar(1) ,
slf_pay_nq_mk varchar(1) ,
in_out_upd_mk varchar(1) ,
mnl_conf_vio varchar(1) ,
remit_cd varchar(1) ,
iit_upd_reas_cd varchar(1) ,
incm_adj varchar(1) ,
xmp_adj varchar(1) ,
ded_adj varchar(1) ,
cmpt_scope_adj varchar(1) ,
oth varchar(1) ,
dl_pay_date varchar(7) ,
reply_mk varchar(1) ,
reply_hsn_org varchar(5) ,
trf_out_hsn_org varchar(5) ,
py_mrg_rfn varchar(17) ,
spr_paid_mk varchar(1) ,
extend_reas_cd varchar(1) ,
extend_date varchar(7) ,
apl_int decimal(14,0) ,
unpaid_cd varchar(1) ,
unpaid_tax decimal(14,0) ,
slf_pay_paid_idn varchar(10) ,
slf_pay_paid_amt decimal(14,0) ,
invt_credit_mk varchar(1) ,
iit_abnor_pr_mk varchar(13) ,
vio_mk varchar(1) ,
adm_rmd_mk varchar(1) ,
asg_mk varchar(1) ,
adm_rmd_stus varchar(1) ,
dly_pay_amt decimal(14,0) ,
adm_rmd_int decimal(14,0) ,
upd_mk varchar(1) ,
tpr_addr_hsn_cd varchar(1) ,
tpr_addr_town_cd varchar(2) ,
tpr_addr_vill_cd varchar(2) ,
tpr_addr_hsn_nm varchar(3) ,
tpr_addr_town_nm varchar(5) ,
tpr_addr_vill_nm varchar(5) ,
tpr_addr_lin varchar(5) ,
tpr_addr_road_no varchar(100) ,
tpr_comu_hsn_cd varchar(1) ,
tpr_comu_town_cd varchar(2) ,
tpr_comu_vill_cd varchar(2) ,
tpr_comu_hsn_nm varchar(3) ,
tpr_comu_town_nm varchar(5) ,
tpr_comu_vill_nm varchar(5) ,
tpr_comu_lin varchar(5) ,
tpr_comu_road_no varchar(100) ,
addr_incon_mk varchar(1) ,
apl_pr_mk varchar(1) ,
force_mk varchar(1) ,
lse_incm_mk varchar(1) ,
prof_mk varchar(1) ,
chk_suc_mk varchar(1) ,
suc_mk varchar(1) ,
suc_suc_mk varchar(1) ,
refd_mk varchar(1) ,
base_tax_mk varchar(1) ,
base_tax_coll_mk varchar(1) ,
spr_levy_incm_amt decimal(14,0) ,
sel_splvy_rate decimal(2,0) ,
sel_splvy_pybl_tax decimal(14,0) ,
cal_tax_days decimal(3,0) ,
rsdt varchar(1) ,
spr_ctx decimal(14,0) ,
full_amt_xmp_std varchar(1) ,
incm_b_date varchar(7) ,
incm_e_date varchar(7) ,
apl_mk varchar(1) ,
tax_rate1 decimal(2,0) ,
tax_rate2 decimal(2,0) ,
tax_rate3 decimal(2,0) ,
tax_rate4 decimal(2,0) ,
tax_rate5 decimal(2,0) ,
apcb_incm_amt1 decimal(14,0) ,
apcb_incm_amt2 decimal(14,0) ,
apcb_incm_amt3 decimal(14,0) ,
apcb_incm_amt4 decimal(14,0) ,
apcb_incm_amt5 decimal(14,0) ,
org_cd varchar(3) ,
user_id_cd varchar(8) ,
update_user_id_nm varchar(20) ,
update_seq_no varchar(3) ,
update_ctrl_area varchar(2) ,
update_sys_tp varchar(3) ,
update_date_time varchar(13) ,
time_stamp date ,
spous_addr_hsn_cd varchar(1) ,
spous_addr_hsn_nm varchar(3) ,
spous_addr_town_cd varchar(2) ,
spous_addr_town_nm varchar(5) ,
spous_addr_vill_cd varchar(2) ,
spous_addr_vill_nm varchar(5) ,
spous_addr_lin varchar(5) ,
spous_addr_road_no varchar(100) ,
anno_date varchar(7) ,
anno_mk varchar(1) ,
child_edu_pers_cnt decimal(2,0) ,
child_edu_ded decimal(14,0) ,
zp_ovrse_slry_tot decimal(14,0) ,
ovrse_ss_tot decimal(14,0) ,
dmst_ss_tot decimal(14,0) ,
scts_trade_incm_tot decimal(14,0) ,
scts_trade_incm_tax decimal(14,0) ,
tpr_incm_tot decimal(14,0) ,
spous_incm_tot decimal(14,0) ,
tpr_prop_loss_ded decimal(14,0) ,
spous_prop_loss_ded decimal(14,0) ,
tpr_saving_incm decimal(14,0) ,
spous_saving_incm decimal(14,0) ,
depnt_saving_incm decimal(14,0) ,
apl_base_live_exp decimal(14,0) ,
apl_base_live_dif decimal(14,0) ,
tax_avoid_mk varchar(1) ,
cal_mode_mrgdivd varchar(1) ,
divd_pf_tot_amt decimal(14,0) ,
divd_pf_pt_crd decimal(14,0) ,
divd_pf_spr_pybl decimal(14,0) ,
apl_base_live_tot decimal(14,0) ,
tpr_profl_samt decimal(14,0) ,
spous_profl_samt decimal(14,0) ,
inves_bdate varchar(7) ,
separate_inform_mk varchar(1) ,
levy_start_date varchar(7) ,
levy_pd varchar(2) ,
levy_rmk varchar(1) ,
ltc_pers_cnt decimal(2,0) ,
ltc_ded decimal(14,0) ,
tpr_nco_sub_amt decimal(14,0) ,
ss_nco_sub_amt decimal(14,0) ,
depnt_nco_sub_amt decimal(14,0) ,
tot_nco_sub_amt decimal(14,0) ,
tpr_dmst_slry_rvnu decimal(14,0) ,
ss_dmst_slry_rvnu decimal(14,0) ,
tpr_ovrse_slry_rvnu decimal(14,0) ,
ss_ovrse_slry_rvnu decimal(14,0) ,
stage_upd_stus char(1) )
TABLESPACE sbd 
DISTRIBUTED BY (rfn)
;

ALTER TABLE  oltp.sbd_ifxt100_h01 OWNER TO ap_sbd;

ALTER TABLE ONLY  oltp.sbd_ifxt100_h01 ADD CONSTRAINT sbd_ifxt100_h01_PK PRIMARY KEY (rfn);
