
-- Schema:  oltp; 
-- Version: V0.09_20210505;
-- Author/Date: cfchen/20210505;
-- Purpose: Oltp資料表;
-- Table: sbd_nigt001_a05;
-- Compressed: N ;
-- Distributed: Y (dlv_unit,tax_cd,flg_tp,serial_no);
-- Partition: N ;
-- Constraint: N

---- Compressed Example: WITH (APPENDONLY=true, COMPRESSLEVEL=1, COMPRESSTYPE=quicklz, OIDS=FALSE)
---- Partition Example: PARTITION BY RANGE(DATA_YM) (PARTITION P201501 START ('2015-01-01'::date) END ('2015-02-01'::date) , ... )
---- Distributed Example: DISTRIBUTED BY (BAN)
---- Naming Convention: P -> pk, U -> uk

DROP TABLE IF EXISTS  oltp.sbd_nigt001_a05;

CREATE TABLE  oltp.sbd_nigt001_a05 (
dlv_unit varchar(3) NOT NULL,
tax_cd varchar(2) NOT NULL,
dlv_yr varchar(3) NOT NULL,
flg_tp varchar(1) NOT NULL,
serial_no varchar(5) NOT NULL,
case_tp varchar(1) ,
vio_host_idn_ban varchar(10) ,
vio_host_nm varchar(100) ,
addr_hsn_nm varchar(20) ,
addr_town_nm varchar(20) ,
addr_vill_nm varchar(20) ,
addr_lin varchar(20) ,
addr_road_no varchar(50) ,
addr_mk varchar(1) ,
zip_cd varchar(20) ,
ban varchar(8) ,
resp_idn varchar(20) ,
resp_nm varchar(30) ,
vio_yr varchar(3) ,
evade_incm decimal(14,0) ,
evade_tax decimal(14,0) ,
beh_amt decimal(14,0) ,
coll_unit varchar(4) ,
bill_unit varchar(4) ,
town_cd varchar(2) ,
serv_area varchar(2) ,
ba_tax_mk varchar(1) ,
ba_tax_key varchar(24) ,
subtax_cd varchar(1) ,
apl_limit_ym varchar(7) ,
invs1 varchar(4) ,
invs2 varchar(4) ,
invs_ratio1 decimal(1,0) ,
invs_ratio2 decimal(1,0) ,
seize_date varchar(7) ,
cpt varchar(4) ,
cpt_cdc_date varchar(7) ,
cpt_cdc_char varchar(16) ,
cpt_cdc_no varchar(11) ,
asst1 varchar(4) ,
asst_cdc_date1 varchar(7) ,
asst_cdc_char1 varchar(16) ,
asst_cdc_no1 varchar(11) ,
asst2 varchar(4) ,
asst_cdc_date2 varchar(7) ,
asst_cdc_char2 varchar(16) ,
asst_cdc_no2 varchar(11) ,
asst3 varchar(4) ,
asst_cdc_date3 varchar(7) ,
asst_cdc_char3 varchar(16) ,
asst_cdc_no3 varchar(11) ,
asst_tp varchar(1) ,
urgt_lmt_date varchar(7) ,
acs_no varchar(11) ,
trstr_cd varchar(5) ,
manage_cd varchar(24) ,
asg_key varchar(50) ,
asg_mk varchar(1) ,
create_date varchar(7) ,
prst_prcd_stus varchar(2) ,
prst_prcd_date varchar(7) ,
o_adtr_cd varchar(5) ,
o_asg_date varchar(7) ,
o_sh_fsh_date varchar(7) ,
prst_adtr_cd varchar(5) ,
prst_asg_date varchar(7) ,
prst_sh_fsh_date varchar(7) ,
extd_tms decimal(2,0) ,
extd_reas varchar(1) ,
crml_stus varchar(2) ,
crml_proc_date varchar(7) ,
crml_artc varchar(4) ,
adtr_apl_tp varchar(1) ,
yn_arrg_mtg varchar(1) ,
adtr_fnsh_date varchar(7) ,
arrg_mtg_tp varchar(1) ,
evd_artc1 varchar(7) ,
evd_amt1 decimal(14,0) ,
evd_artc2 varchar(7) ,
evd_amt2 decimal(14,0) ,
bhv_artc1 varchar(7) ,
bhv_amt1 decimal(14,0) ,
bhv_artc2 varchar(7) ,
bhv_amt2 decimal(14,0) ,
fine_amt_tot decimal(14,0) ,
vio_fact_cd1 varchar(2) ,
vio_fact_cd2 varchar(2) ,
fsh_apl_tp varchar(1) ,
fsh_date varchar(7) ,
carry_date varchar(7) ,
carry_seq_no varchar(4) ,
adm_rmd_stus varchar(2) ,
adm_rmd_date varchar(7) ,
upd_jdgf_stus varchar(2) ,
upd_jdgf_date varchar(7) ,
re_chk_unit varchar(4) ,
madtr_cd varchar(5) ,
pnsh_pr_mk varchar(1) ,
pnsh_tp varchar(5) ,
ovpnsh_mk varchar(1) ,
npnsh_cd varchar(4) ,
revo_cd varchar(4) ,
f_cnvt_mk varchar(1) ,
update_user_cd varchar(8) ,
update_date varchar(7) ,
vio_b_date varchar(7) ,
vio_e_date varchar(7) ,
auth_mk varchar(1) ,
bhv_amt decimal(14,0) ,
time_stamp timestamp(6) ,
adt_sgst_mk varchar(1) ,
chk_unit varchar(3) ,
evd_artc3 varchar(7) ,
evd_amt3 decimal(14,0) ,
evd_artc4 varchar(7) ,
evd_amt4 decimal(14,0) ,
bhv_artc3 varchar(7) ,
bhv_amt3 decimal(14,0) ,
bhv_artc4 varchar(7) ,
bhv_amt4 decimal(14,0) ,
npnsh_reas varchar(100) ,
resp_addr varchar(400) ,
is_reported_case varchar(1) ,
dlv_vio_reas varchar(1) ,
tax_avoid_mk varchar(1) ,
untr_slry_mk varchar(1) ,
op_mk varchar(1) ,
vio_host_roman_nm varchar(200) ,
resp_roman_nm varchar(200) ,
stage_upd_stus char(1) )
TABLESPACE sbd 
DISTRIBUTED BY (dlv_unit,tax_cd,flg_tp,serial_no)
;

ALTER TABLE  oltp.sbd_nigt001_a05 OWNER TO ap_sbd;

ALTER TABLE ONLY  oltp.sbd_nigt001_a05 ADD CONSTRAINT sbd_nigt001_a05_PK PRIMARY KEY (dlv_unit,tax_cd,dlv_yr,flg_tp,serial_no);
